name: Update Commit Count
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Fetch Commits and Repos
        env:
          GH_TOKEN: ${{ secrets.COMMIT_TOKEN }}
        run: |
          COUNT=$(curl -H "Authorization: bearer $GH_TOKEN" -X POST -d '{"query":"{user(login:\"BrentanRath\"){contributionsCollection{contributionCalendar{totalContributions}}}}"}' https://api.github.com/graphql | jq '.data.user.contributionsCollection.contributionCalendar.totalContributions')
          REPOS=$(curl -H "Authorization: bearer $GH_TOKEN" -X POST -d '{"query":"{user(login:\"BrentanRath\"){repositories(privacy:PUBLIC){totalCount}}}"}' https://api.github.com/graphql | jq '.data.user.repositories.totalCount')
          STARTED=$(curl -H "Authorization: bearer $GH_TOKEN" -X POST -d '{"query":"{user(login:\"BrentanRath\"){repositories(first:100,privacy:PUBLIC){nodes{stargazerCount}}}}"}' https://api.github.com/graphql | jq '[.data.user.repositories.nodes[].stargazerCount] | add // 0')
          echo "{\"totalCommits\": $COUNT, \"publicRepos\": $REPOS, \"thingsStarted\": $STARTED}" > data.json
      - name: Commit and Push
        run: |
          git config user.name "github-actions"
          git config user.email "action@github.com"
          git add data.json
          git commit -m "Update commit count" || exit 0
          git push